# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    movie_db.url: '%env(MOVIE_DB_URL)%'
    movie_db.key: '%env(MOVIE_DB_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    # App\:
    #     resource: '../src/'
    #     exclude:
    #         - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\MovieCollection\Application\Movie\ListMovies:
        $movieRepositoryInterface: '@App\MovieCollection\Infrastructure\Doctrine\Repository\Movie\DoctrineMovieRepository'

    App\MovieCollection\Application\Movie\CreateMovieFromMovieDBInfo:
        $getMovieDBMovieInfo: '@App\MovieCollection\Infrastructure\HttpClient\MovieDB\GetMovieDBMovieInfo'
        $movieRepository: '@App\MovieCollection\Infrastructure\Doctrine\Repository\Movie\DoctrineMovieRepository'
    
    App\MovieCollection\Infrastructure\Api\:
        resource: '../src/MovieCollection/Infrastructure/Api'
        tags: ['controller.service_arguments']

    App\MovieCollection\Infrastructure\HttpClient\:
        resource: '../src/MovieCollection/Infrastructure/HttpClient'
        tags: ['controller.service_arguments']

    App\MovieCollection\Infrastructure\Doctrine\Repository\:
        resource : '../src/MovieCollection/Infrastructure/Doctrine/Repository'

    App\MovieCollection\Infrastructure\Doctrine\Repository\Movie\DoctrineMovieRepository:
        $movieGenreRepository: '@App\MovieCollection\Infrastructure\Doctrine\Repository\Movie\DoctrineMovieGenreRepository'